Repository mcci-catena/arduino-lorawan, pull requests merged in 2019-07, with the labels that each got.

#105 Fix #104: update 'travis.yml' with new stm32 boards.
  .travis.yml
Labels: enhancement

#109 Update CI
  .travis.yml
Labels: travis

#111 Tweak initial power settings for US
  src/lib/machineq_us915_netbeginregioninit.cpp
  src/lib/ttn_us915_netbeginregioninit.cpp
Labels: enhancement

#114 Prepare v0.6.0 release
  README.md
  VERSION.txt
  library.json
  library.properties
  src/Arduino_LoRaWAN.h
Labels: release
